local TextHelpers = require("scripts.text_helpers")
local DisplayPanelApi = require("__display-panel__.public_api")

local DEFAULT_ALPHA = 0.75
local DEFAULT_WIDTH = 7

---@class GenerationOptions
---@field alpha number
---@field width integer
---@field force_rainbow_fallback boolean

---adds type fluid for signals (if not specified, it is seen as item signal)
---@param fluid_name any
---@return table
local function fluid_signal(fluid_name)
  return {
    type = "fluid",
    name = fluid_name,
  }
end

---------------------------------------------------------------------------------------------------

---filters out hidden entities and blueprint parameters
---@param prototype any
---@return boolean
local function is_real(prototype)
  return prototype and prototype.valid and not prototype.hidden and not prototype.parameter
end

---make sure current modpack has display-panel prototypes
---@return boolean
local function has_display_panel_prototype()
  return prototypes.entity["display-panel"] ~= nil
end

---get sorted table of fluid names
---@return table
local function get_sorted_fluid_names()
  local names = {}

  for name, fluid in pairs(prototypes.fluid) do
    if is_real(fluid) then
      table.insert(names, name)
    end
  end

  table.sort(names)
  return names
end

---------------------------------------------------------------------------------------------------

---Creates blueprint book and iterates over science packs to fill book
---@param player LuaPlayer
---@param generation_options GenerationOptions
local function create_fluidmeter_book(player, generation_options)
  if not player or not player.valid then
    return
  end

  --------------------------

  -- 1. STAGE: Start a fresh book building session for this player in the Core Mod
  -- This will trigger create_active_book_session_structure() and handle the 'or nil' state safely
  remote.call("display_panel_book", "start", player.index)

  -- 2. STAGE: Gather our specific science packs and queue them into the book
  local prototype_names = get_sorted_fluid_names()

  for i, prototype_name in ipairs(prototype_names) do
    blueprints_created = i
    local options = {
      prototype = fluid_signal(prototype_name),
      bar_width = generation_options.width,
      alpha = generation_options.alpha,
      icon = fluid_signal(prototype_name),
    }
    local panel_config = DisplayPanelApi.new_meter(options--[[@as DisplayPanelOptions]])

    -- Add this specific page to the player's active session queue
    remote.call("display_panel_book", "add", player.index, panel_config)
  end

  local book_preview_icons = {
    {
      index = 1,
      signal = { name = "display-panel" },
    },
  }
  for i = 1, math.min(3, #prototype_names) do
    book_preview_icons[#book_preview_icons + 1] = {
      index = i + 1,
      signal = fluid_signal(prototype_names[i]),
    }
  end

  local opacity_percent = generation_options.alpha * 100
  local options_output_string = "(bar width: " .. generation_options.width .. " | opacity: " .. opacity_percent .. "%)"

  local book_label = "Fluidmeter display panels " .. options_output_string
  local book_description = "Generated by display panel fluidmeter mod from current fluid prototypes."

  -- 3. STAGE: Finish the book session and deliver the physical item into the player's hand
  local success =
    remote.call("display_panel_book", "finish", player.index, book_label, book_description, book_preview_icons)

  if success then
    player.print("Fluidmeter blueprint book generated and placed in your cursor!")
  else
    player.print("Failed to generate book. Ensure your science pack list is not empty.")
  end
end

---------------------------------------------------------------------------------------------------

---initiates process - sort-of-main()-function
local function handle_book_command(command)
  if not command.player_index then
    game.print("This command must be run by a player.")
    return
  end

  local player = game.players[command.player_index]
  if not player or not player.valid then
    return
  end

  if not has_display_panel_prototype() then
    player.print("Display panel prototype is not available. Cannot create fluidmeter blueprints.")
    return
  end

  local generation_options = TextHelpers.parse_numerical_parameter(command.parameter)
  local defaults_used = {}

  -- If width was not provided or was invalid, fallback to default
  if not generation_options.width then
    generation_options.width = DEFAULT_WIDTH
    table.insert(defaults_used, "width = " .. generation_options.width)
  end

  if generation_options.width > 24 then
    generation_options.width = 24
    player.print("Factorio only supports bars up to width 24")
  end

  -- If alpha was not provided or was invalid, fallback to default
  if not generation_options.alpha then
    generation_options.alpha = DEFAULT_ALPHA
    table.insert(defaults_used, "alpha = " .. generation_options.alpha)
  end

  -- Print the message to the player if any defaults were applied
  if #defaults_used > 0 then
    local default_fallbacks = table.concat(defaults_used, " | ")
    player.print("Using default values: " .. default_fallbacks)
  end

  -- Rainbow fallback flag (safe against nil command.parameter)
  generation_options.force_rainbow_fallback = command.parameter and command.parameter:find("rainbow") ~= nil

  create_fluidmeter_book(player, generation_options)
end

---------------------------------------------------------------------------------------------------

---add console command for main functionality
commands.add_command(
  "fluidmeter-book",
  "Create a blueprint book. Optionally specify bar width and opacity with 'width=10 opacity=0.75",
  handle_book_command
)
